# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='note',
        ),
    ]
