# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 19:45
from __future__ import unicode_literals

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20171127_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.ForeignKey(on_delete=courses.models.Question, to='courses.Answer'),
        ),
    ]
